### ISSUE TITLE
Dockerize app

### ISSUE THREAD

**Issue by ar-maged** [levelhq/level#85] opened 2018-06-05 02:03 UTC
It would make the development experience so much easier without the hassle of installing the environment dependencies (Elixir, PostgreSQL & Node.js) with their correct versions. It would also help a lot with deployment.

**Comment by ar-maged** [comment] 2018-06-05 02:04
And great work, you guys! 👏👏👏

**Comment by devonestes** [comment] 2018-06-05 07:05
Docker makes deployment for certain kinds of BEAM applications very difficult. It essentially makes releases impossible, and given the nature of this app, there will almost certainly be long-running state (as there is in pretty much every BEAM messaging app), and that means deployment will most likely be done with releases. Unless you have a simple, stateless app (which many people do have!), it’s usually best to rely on the built-in features of the BEAM for deployment.

I would caution _against_ docker for these reasons.

**Comment by derrickreimer** [comment] 2018-06-06 15:50
Thanks guys. I'm going to close this one out for now. Seems like one approach for deployments is to use a Docker container to build releases, which mimics production server environments for compatibility. If that proves to be best practice then we may end up with a Docker image for that purpose -- @devonestes, you would know way more about this than me at this point in time :). We should chat.

**Closed by derrickreimer** 2018-06-06 15:50 UTC

**Comment by tomsun** [comment] 2018-07-10 13:11
> It would make the development experience so much easier without the hassle of installing the environment dependencies

@ar-maged agree!

I usually define my dev environments with Docker, to be able to reproduce them
later more easily, to have them version controlled alongside the project
and to be able to share them. Got curious to poke a bit at Level after Derrick's
last podcast with Rob - and gave this a shot in #97, as part of
getting Level running on my own machine. I.e. a dev-focused docker-compose
environment that installs and caches dependencies. Postgres as a separate container.

(Would have preferred Node.js in its own container to use the official images
and to docker-cache the node modules separately, but would take some refactoring
of Level to support that neatly I guess)

@derrickreimer feel free to embrace or ignore.

**Comment by tomsun** [comment] 2018-07-10 13:14
@devonestes  I.e. Erlang's hot code reloading? added complexity on some level: sure. impossible is a strong word.

- You could look at the container as your host environment, much how you treat
a VM or physical box and update the running container as your primary deployment
strategy (replace files via host bind mounts and / or run concurrent commands
in the container with docker exec...).

- Or you could do what you would do in most other languages: bring up some additional
application processes (containers) with v2 and then gradually retire the v1 processes.
Maybe having all the Erlang nodes networked even retains some of the code-reloading-esk benefits?

One of those topics that could be bike-shedded forever probably... 

> Hot code reloading is always more work than just blue-green and should be avoided if |not] necessary
https://news.ycombinator.com/item?id=10669131

> The sort of problems most people try to solve with Docker (lightweight parallelism, execution environment hygiene, "the network is the abstraction", process isolation, memory safety, etc.) are the problems Erlang already addresses in a more complete fashion.
https://stackoverflow.com/questions/36173583/erlang-elixir-on-docker-and-hot-code-swap

**Comment by tomsun** [comment] 2018-07-10 13:37
> Releases may also contain the Erlang runtime (ERTS, short for Erlang Runtime System Application). Releases that include ERTS are almost completely self-contained. They have no external dependencies except for true essentials such as libc or openssl 
https://medium.com/@pentacent/elixir-releases-docker-the-basics-explained-4c800a5b990b

Alright, at that point the *production* Dockerfile would indeed be quite thin.
Perhaps one factor is whether you're happy with VM-based auto-scaling tools
or prefer Docker-based orchestration (Kubernetes etc)

(assuming you even need to scale up and down automatically - maybe you don't)

**Comment by devonestes** [comment] 2018-07-10 14:15
The gist of it is, if you have persistent in-memory state in your application (i.e. in a GenServer), restarting your application, or any node of your application, is a huge bummer. Releases give you the ability to push new code without having to restart your application, thus maintaining the in-memory state. To the best of my knowledge, deploying a new Docker image always involves restarting that node when it's deployed, meaning any state stored in memory is wiped and needs to be repopulated.

Given the nature of this app (messaging), it will almost certainly involve large amounts of in-memory state (assuming it's architected in the way many other Erlang/Elixir messaging apps are) so they can leverage the soft real-time benefits of the BEAM. That tells me that, most likely, this application wouldn't benefit from running in any sort of container in production that requires a reboot of any node on a given deployment.

That said, I'm no ops expert, so there may be something I'm missing here. What I do know, however, is that the Elixir community and core team is putting a lot of time and effort into making releases as easy as possible, and encouraging them as the default way to deploy Elixir applications in the future, which I see as a big win since all Elixir applications will be able to leverage the work done by these people with expert level knowledge of the BEAM.

**Comment by derrickreimer** [comment] 2018-07-10 14:47
I appreciate the thoughts guys, I have much to learn in this area still and will keep all this in mind as I move closer to getting real prod deployments sorted.
